### ISSUE TITLE
Artifacts are not available via Nuget feed

### ISSUE THREAD

**Issue by t3r5e** [JetBrains/teamcity-azure-storage#1]
When this plugin is enabled, the artifacts publish great to Azure storage. However those artifacts are not available to be pulled via the nuget feed. Am I missing a configuration?

**Comment by dtretyakov** [comment]
@t3r5e, thanks for reporting. It looks like a bug in the [NuGet plugin](https://github.com/JetBrains/teamcity-nuget-support). We'll verify and fix it.

Do you publish nuget packages via `NuGet Publish` build step or via `Artifact paths` at the General Build configuration page?

**Comment by t3r5e** [comment]
@dtretyakov I am using the built in nuget feed that uses the artifact path. Thank you

**Comment by dtretyakov** [comment]
@t3r5e, could you please try upgrading [plugin](https://plugins.jetbrains.com/plugin/9617-azure-artifact-storage) where was fixed issue with artifacts upload [TW-49702](https://youtrack.jetbrains.com/issue/TW-49702).

Could you also please provide detailed error message?

**Comment by dtretyakov** [comment]
Since TeamCity 2018.1 by default enabled [agent side NuGet packages indexing](https://youtrack.jetbrains.com/issue/TW-49713) which solves the problem.
