### ISSUE TITLE
The link cache hangs on to the SAS urls too long

### ISSUE THREAD

**Issue by droyad** [JetBrains/teamcity-azure-storage#13]
The [myLinksCache](https://github.com/JetBrains/teamcity-azure-storage/blob/d27af8dd3ca12b12c9f123fca858682e2fd6c1e3/azure-storage-server/src/main/kotlin/jetbrains/buildServer/serverSide/artifacts/azure/web/AzureArtifactDownloadProcessor.kt#L38) expires items after [urlLifeTime](https://github.com/JetBrains/teamcity-azure-storage/blob/d27af8dd3ca12b12c9f123fca858682e2fd6c1e3/azure-storage-server/src/main/kotlin/jetbrains/buildServer/serverSide/artifacts/azure/web/AzureArtifactDownloadProcessor.kt#L62). The Azure URLs are [generated](https://github.com/JetBrains/teamcity-azure-storage/blob/d27af8dd3ca12b12c9f123fca858682e2fd6c1e3/azure-storage-server/src/main/kotlin/jetbrains/buildServer/serverSide/artifacts/azure/web/AzureArtifactDownloadProcessor.kt#L93) using that exact [same duration](https://github.com/JetBrains/teamcity-azure-storage/blob/d27af8dd3ca12b12c9f123fca858682e2fd6c1e3/azure-storage-server/src/main/kotlin/jetbrains/buildServer/serverSide/artifacts/azure/web/AzureArtifactDownloadProcessor.kt#L51-L53). The default is 60 seconds.

The overall process is:
1. Calculate the link expiry date
2. Request a URL for that expiry date
3. Add the URL to the cache
4. [Just under 60 seconds passes]
5. Another build needs the link
6. The link is in the cache, that link is returned
7. The link is used to download the file

The time between step 1 and 3, and step 6 and 7 is non-zero. Therefore the cache can return a link that is almost expired or has expired very recently.

My suggestion is that the url expiry is twice that of the cache time. A cache time of 60 seconds seems reasonable.

**Comment by IlyaFomenko** [comment]
@droyad It was not a trivial problem. Thank you for your investigation!
I added a separate internal property for configuring the max-age for http cache. By default it is twice shorter than the link expiration time.
Please see https://github.com/JetBrains/teamcity-azure-storage/commit/092e8645666620329a15a406cebde0d95f9159df

**Comment by matt-richardson** [comment]
Unfortunately, this issue is still occurring :(

**Comment by droyad** [comment]
@IlyaFomenko I think there is a still a problem as the `myLinksCache` still hangs onto the URL for the exact time it is valid for. I've created a new PR #15 with a suggested fix.
