### ISSUE TITLE
Parallel upload to Azure Blob Storage

### ISSUE THREAD

**Issue by pritchin** [JetBrains/teamcity-azure-storage#4]
Our artifact has size around 1GB and it's upload is too slow. 
![image](https://user-images.githubusercontent.com/5250800/28490809-e40cb930-6eeb-11e7-92db-9cb304fc1203.png)

At the same time Azure Blob Storage client for Java has special property which enables concurrent requests `ConcurrentRequestCount` https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.storage.file._file_request_options.setconcurrentrequestcount

I changed file `azure-storage-agent/src/main/kotlin/jetbrains/buildServer/artifacts/azure/publish/AzureArtifactsPublisher.kt` in function  AzureArtifactsPublisher
```java
                    val blobOptions = BlobRequestOptions()
                    blobOptions.concurrentRequestCount = 8
                     FileInputStream(file).use {
                         val length = file.length()
                        blob.upload(it, length, null, blobOptions, null)
                         val artifact = ArtifactDataInstance.create(filePath, length)
                         publishedArtifacts.add(artifact)
                     }
```
Then I build plugin with Grandle and change zip file on TeamCity agent machine. The result is so good:
![image](https://user-images.githubusercontent.com/5250800/28490740-37f685d2-6eea-11e7-9f87-2b6d71ee19ed.png)
I would be nice to realize the parallel upload.

**Comment by dtretyakov** [comment]
@pritchin, thanks it was fixed in the latest plugin build:
https://plugins.jetbrains.com/plugin/9617-azure-artifact-storage

**Comment by sorenhansendk** [comment]
Hmm. On the plugin page you linked to is the latest update from 7. april? 🤔

**Comment by dtretyakov** [comment]
@sorenhansendk, don't pay attention to this date, it's creation date of this plugin page in the plugins repository.

The download link will redirect you to the latest plugin build, which at the moment should be 0.5.0.
