### ISSUE TITLE
Add Azure Storage Blob Upload build step

### ISSUE THREAD

**Issue by jaredcnance** [JetBrains/teamcity-azure-storage#8]
By default, when artifacts are uploaded to Azure Blob Storage, they will be uploaded in the nested path structure:
```
container/
└── Project
    └── Project_Build
        └── 100
            ├── my-app-1521658753171-43bb3c049af9850c75a9.js
            └── my-app-latest.js
```

However, I want to upload blobs to a well-known location such as:

```
container/
├──  my-app-1521658753171-43bb3c049af9850c75a9.js
└──  my-app-latest.js
```

Is this currently possible? It would also require overwriting any existing files with the same path (e.g. `my-app-latest.js`)

**Comment by dtretyakov** [comment]
@jaredcnance, currently Artifacts storage plugins are indented for replacement of internal TeamCity storage, so for them very important that file structure does not have conflicts.

To cover your case we need to add a build step which could upload build artifacts into custom Azure Blob Container with customizable path.

**Comment by jaredcnance** [comment]
Okay thanks! Turns out is is much simpler to just use [Azure's CLI](https://docs.microsoft.com/en-us/azure/storage/common/storage-azure-cli#create-and-manage-blobs) to accomplish this task. I'm going to close the issue since I no longer require it, but feel free to re-open it if it's something you want to move forward with.
