### ISSUE TITLE
Does not work with Azure Static website (Azure blob storage with `$web` container)

### ISSUE THREAD

**Issue by anujku** [JetBrains/teamcity-azure-storage#9]
Azure static website has a container named `$web`. The plugin always creates a folder with name `web` instead. If you specify the path it still pushes the artifacts to `web` folder instead of `$web`

**Comment by undimmable** [comment]
This plugin is only intended for storing artifacts, not for deploying static websites. If you want to deploy a website, please consider using azure cli.
